[package]
name = "actify-macros"
version = "0.6.0"
description = "Actify's procedural macros"
documentation = "https://docs.rs/actify-macros/latest/actify_macros/"
readme = "README.md"
keywords = ["actor", "async", "macro", "proc-macro", "tokio"]
categories = ["asynchronous", "development-tools::procedural-macro-helpers"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
