[package]
name = "actify-macros"
version = "0.2.0"
edition = "2021"
description = "Actify's procedural macros"
license = "MIT"

[dependencies]
quote = "1.0"
syn = {version = "1.0", features = ["full"] }
proc-macro2 = "1.0"

[lib]
proc-macro = true